version: "3.9"
services:
  mongo:
    image: mongo:5.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: bookgraph
    ports:
      - target: 27017
        published: 27017
    volumes:
      # - ./mongo_initdb:/docker-entrypoint-initdb.d
      - type: volume
        source: mongo_data
        target: /data/db
volumes:
  mongo_data:
