[formatter.alejandra]
command = "alejandra"
includes = ["*.nix"]

[formatter.yamlfmt]
command = "yamlfmt"
includes = [
  "*.yml",
  "*.yaml",
]
excludes = [
  "pnpm-lock.yaml",
]

[formatter.dprint]
command = "dprint"
options = ["fmt"]
includes = [
  "*.json",
  "*.toml",
  "*.md",
  "*.ts",
]
excludes = [
  "sampledata/**/*.ts",
]

[formatter.deno-fmt]
command = "deno"
options = ["fmt"]
includes = ["sampledata/**/*.ts"]
