[formatter.alejandra]
command = "alejandra"
includes = ["*.nix"]

[formatter.yamlfmt]
command = "yamlfmt"
includes = [
  "*.yml",
  "*.yaml",
]

[formatter.dprint]
command = "dprint"
options = ["fmt"]
includes = [
  "*.json",
  "*.toml",
  "*.md",
]
